### PR TITLE
fix body hash issue in relaxe mode #38

### PR DESCRIPTION
**Pull request by mschneider82**
I have added a test which failed before. With this fix i can sucessfully verify my testmail which was valid but the libray said body hash missmatch.

verify issue described in #38

### CODE REVIEW

**Review by mschneider82 — COMMENTED** [review]
since `res` has the same size(length) as the input `b` we cannot add `\n` when the last char is `\r`, so we need to remove the `\r` (only in relaxed mode).

**Comment by emersion** [comment]
So, it seems like you're doing essentially this:

```go
b = bytes.TrimRight(b, "\r")
```

ie. removing trailing `\r` if any. Is this correct?

This should likely be part of the `relaxedBodyCanonicalizer.Write` loop, because it's specific to the relaxed mode.

* * *

This seems to be yet another quirk for relaxed mode. [The RFC](https://tools.ietf.org/html/rfc6376#section-3.4.4) doesn't seem to mention it. Or maybe it's part of "Ignore all whitespace at the end of lines"? Or maybe "Ignore all empty lines at the end of the message body"?

**Comment by mschneider82** [comment]
@emersion  yes its basicly `bytes.TrimRight`, but i just remove exact one `\r` at the end. not more (TrimRight would could trim more than one).

**Comment by mschneider82** [comment]
are you thinking about?

```
b = fixCRLF(b)
b = bytes.TrimRight(b, "\r")
```

**Comment by emersion** [comment]
Hmm, wait. Your bug only happens when a slice passed to `Write` ends with a `\r`. That likely happens because a CRLF sequence is split between two `Write` calls:

```go
Write([]byte("line1\r"))
Write([]byte("\nline2"))
```

I've written a failing test:

```go
func TestRelaxedCanonicalizer_CanonicalBody_splitCRLF(t *testing.T) {
	want := "line 1\r\nline 2\r\n"
	writes := [][]byte{
		[]byte("line 1\r"),
		[]byte("\nline 2"),
	}

	var b bytes.Buffer
	wc := new(relaxedCanonicalizer).CanonicalizeBody(&b)
	for _, b := range writes {
		if _, err := wc.Write(b); err != nil {
			t.Errorf("Expected no error while writing to relaxed body canonicalizer, got: %v", err)
		}
	}
	if err := wc.Close(); err != nil {
		t.Errorf("Expected no error while closing simple body canonicalizer, got: %v", err)
	} else if s := b.String(); s != want {
		t.Errorf("Expected canonical body to be %q, but got %q", want, s)
	}
}
```

**Comment by emersion** [comment]
Superseded by https://github.com/emersion/go-msgauth/pull/39

**Pull request closed without merging**
